site: 
  title: nREPL
  url: https://nrepl.org/ 
  start_page: nrepl::index.adoc 
content: 
  sources: 
  - url: /home/dominic/src/github.com/nrepl/nREPL #https://github.com/SevereOverfl0w/nREPL.git 
    branches: ['HEAD'] 
    # tags: v3.* 
    start_path: doc
asciidoc: 
  attributes: 
    linkattrs: ''
    toc: ~
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output: 
  clean: true 
  dir: ./public 
